### ISSUE TITLE
Roadmap to stable release

### ISSUE THREAD

**Issue by pradyunsg** [pradyunsg/sphinx-basic-ng#1]
TBD

**Comment by pradyunsg** [comment]
- [ ] https://sphinx-basic-ng.readthedocs.io/en/latest/usage/skeleton/
- [ ] https://sphinx-basic-ng.readthedocs.io/en/latest/development/
- [ ] https://sphinx-basic-ng.readthedocs.io/en/latest/design/

**Comment by pradyunsg** [comment]
OK, I think I'm basically ready to call this 1.0.0 once the documentation work is done.

If the folks watching this repository have thoughts on more things that this might need to be considered good-enough to have a stability policy, lemme know! ^>^
