### ISSUE TITLE
Brainstorm some components that should be in this theme

### ISSUE THREAD

**Issue by choldgraf** [pradyunsg/sphinx-basic-ng#11]
In addition to the basic template structure, I think a few components could be useful to include as they will be really common across all themes. What would this list look like?

In my mind, there are two design cases that we could consider, and then figure out the most common patterns that would be repeated across all of them.

### For a standard left-sidebar theme:

- [x] ~A site-wide Table of Contents~ (`{{ toctree(...) }}` is sufficient for now)

### For a top navbar theme

This theme has a top navbar with navigation and "more stuff in general" and a left-sidebar for an in-section navigation.

- [ ] A top-headers only Table of Contents
- [ ] A Table of Contents that starts at level 2 and otherwise behaves like `{{ toctree(...) }}`

### Shared

- [x] Display a logo (#14)
- [x] ~Display the site name~ (`{{ doctitle }}` is sufficient)
- [x] ~Display the in-page table of contents~ (`{{toc}}` is sufficient)
- [x] Previous / next buttons (#15)
- [x] Sphinx Ethical Ads HTML (#14)
- [x] Breadcrumbs (#14)
- [x] "Edit this page" (#14)
- [x] Search bar HTML
- [x] Hide highlights link/button, after search

### A few fancier components (maybe delegated to themes?)

1. A list of FontAwesome icons + links for each button (basically, [the pydata link behavior](https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/configuring.html#configure-icon-links))
2. Text defined in config that becomes footer text (since most users probably don't want to have to write custom HTML templates in order to take advantage of the "footer" section)
3. Text defined in config that becomes announcement text (for the same reason)

Any thoughts on this?

**Comment by pradyunsg** [comment]
Breadcrumbs would be another thing.

**Comment by pradyunsg** [comment]
> 1. A list of FontAwesome icons + links for each button

I'm a strong -1 on adding a dependency/vendoring Font Awesome in this theme directly, but I'm on board for having something that needs the downstream theme to declare the config option, add font-awesome however it wants, and include the component somewhere on the page. :)

**Comment by pradyunsg** [comment]
I'll actually break out the RTD things into a separate issue, so that we can have a back-and-forth with RTD folks on that! :)

**Comment by humitos** [comment]
> > Previous / next buttons
> 
> This is tricky to make into a component, since there's lots of ways to do it. Should I just pick one of no-svg-or-asset-dependencies approach and use that here?

Whatever that way is, I'd suggest to show the name of the section you are accessing on those buttons as well. Just "Next" and "Previous" buttons are terrible to me. I love the ones that have both:

```
>> Next
Installation Guide
```

```
<< Previous
What are this docs?
```

I think it's way clearer where are you going if you click those buttons.

**Comment by pradyunsg** [comment]
I took the liberty of editing the issue description, into a checklist; crossing off the things that we seem to agree won't need dedicated components.

I've also added "hide this search", which is something that Sphinx's own documentation has but I haven't seen in too many other themes; and it's useful.

**Comment by mgeier** [comment]
Regarding "hide search highlighting", see also https://github.com/readthedocs/sphinx_rtd_theme/issues/816 and https://github.com/readthedocs/sphinx_rtd_theme/pull/876.

My own Sphinx theme has a quite prominent button (or rather link) for this: https://insipid-sphinx-theme.readthedocs.io/en/0.2.4/intro.html?highlight=topbar#features

**Comment by pradyunsg** [comment]
Ah yes!

Insipid was where I'd seen it for the first time! Thanks for chiming in @mgeier! :)

**Comment by pradyunsg** [comment]
I think 0.0.1.alpha3 is the first experimentally-usable release of this theme.

I've got the off-canvas sidebars working, things need accessibility labels and the documentation needs a lot more words; but the basic scaffolding and core concept of this project are set up now. Now for the long tail of rounding out the rough edges, and figuring out the fun bits! :)

**Comment by pradyunsg** [comment]
Also, the docs are up, and the changelog is at: https://sphinx-basic-ng.readthedocs.io/en/latest/changelog/

**Comment by pradyunsg** [comment]
With the most recent pushes, I've added all the non-navigational components. With that, I'm going to close this.

I'll create a separate issue to discuss and track adding navigational stuff!
